<?php
/**
 * Magecom
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magecom.net so we can send you a copy immediately.
 *
 * @category    Design
 * @package     Magecom_Package
 * @copyright Copyright (c) 2017 Magecom, Inc. (http://www.magecom.net)
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @var \Magecom\Brand\Block\Brand\ListProduct $block
 */
$products = $block->getProductsByCurrentBrand();
?>
<ul>
<?php
/**
 * @var \Magento\Catalog\Model\Product $product
 */
foreach ($products as $product) {
?>
<li><a href="<?php echo $product->getProductUrl() ?>">
        <?php echo  $product->getName().$product->getData('sku') ?>
    </a></li>
<?php
}
?>

</ul>